-- Database
CREATE DATABASE AULA10;

-- Seta Database
USE AULA10;

-- Table Cliente
CREATE TABLE CLIENTE
( CODIGO INT AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PRIMARY KEY(CODIGO));

-- Insert Cliente
INSERT INTO CLIENTE
     VALUES (1,'CARLOS EDUARDO DOS SANTOS LEITE','eduardo10.smart@gmail.com');

-- Select Cliente
SELECT * FROM CLIENTE;
